// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2WjlfBdORvIwas8M4--fejDNGjK994Xk',
    appId: '1:659082750983:web:67e7e9899cc2adfafe0ea2',
    messagingSenderId: '659082750983',
    projectId: 'maps-3759d',
    authDomain: 'maps-3759d.firebaseapp.com',
    storageBucket: 'maps-3759d.firebasestorage.app',
    measurementId: 'G-BC4PFP93Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQ23PO3d3wn0v4JNg0w9PMN-7guh1drE',
    appId: '1:659082750983:android:c8b1079782da3090fe0ea2',
    messagingSenderId: '659082750983',
    projectId: 'maps-3759d',
    storageBucket: 'maps-3759d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4pLH0fbKPZ7h_Iya95f8lhDKuMCjtsQ',
    appId: '1:659082750983:ios:7653692b2b1225f3fe0ea2',
    messagingSenderId: '659082750983',
    projectId: 'maps-3759d',
    storageBucket: 'maps-3759d.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo4pLH0fbKPZ7h_Iya95f8lhDKuMCjtsQ',
    appId: '1:659082750983:ios:7653692b2b1225f3fe0ea2',
    messagingSenderId: '659082750983',
    projectId: 'maps-3759d',
    storageBucket: 'maps-3759d.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2WjlfBdORvIwas8M4--fejDNGjK994Xk',
    appId: '1:659082750983:web:8726bf3a4c2786e5fe0ea2',
    messagingSenderId: '659082750983',
    projectId: 'maps-3759d',
    authDomain: 'maps-3759d.firebaseapp.com',
    storageBucket: 'maps-3759d.firebasestorage.app',
    measurementId: 'G-EGLSV4J0CC',
  );
}
